cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64.xml  kernel_platform/common/android/abi_gki_aarch64.xml 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_exynos  kernel_platform/common/android/abi_gki_aarch64_exynos 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_exynosauto  kernel_platform/common/android/abi_gki_aarch64_exynosauto 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_galaxy  kernel_platform/common/android/abi_gki_aarch64_galaxy 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_imx  kernel_platform/common/android/abi_gki_aarch64_imx 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_mtk  kernel_platform/common/android/abi_gki_aarch64_mtk 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_oplus  kernel_platform/common/android/abi_gki_aarch64_oplus 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_pixel  kernel_platform/common/android/abi_gki_aarch64_pixel 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_qcom  kernel_platform/common/android/abi_gki_aarch64_qcom 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_unisoc  kernel_platform/common/android/abi_gki_aarch64_unisoc 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_virtual_device  kernel_platform/common/android/abi_gki_aarch64_virtual_device 
cp /home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_xiaomi  kernel_platform/common/android/abi_gki_aarch64_xiaomi 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/asm/cache.h  kernel_platform/common/arch/arm64/include/asm/cache.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/asm/kvm_pkvm.h  kernel_platform/common/arch/arm64/include/asm/kvm_pkvm.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/asm/mte-kasan.h  kernel_platform/common/arch/arm64/include/asm/mte-kasan.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/asm/mte.h  kernel_platform/common/arch/arm64/include/asm/mte.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/asm/percpu.h  kernel_platform/common/arch/arm64/include/asm/percpu.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/asm/pgtable-prot.h  kernel_platform/common/arch/arm64/include/asm/pgtable-prot.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/asm/pgtable.h  kernel_platform/common/arch/arm64/include/asm/pgtable.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/include/uapi/asm/setup.h  kernel_platform/common/arch/arm64/include/uapi/asm/setup.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/cpufeature.c  kernel_platform/common/arch/arm64/kernel/cpufeature.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/head.S  kernel_platform/common/arch/arm64/kernel/head.S 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/image.h  kernel_platform/common/arch/arm64/kernel/image.h 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/mte.c  kernel_platform/common/arch/arm64/kernel/mte.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/perf_event.c  kernel_platform/common/arch/arm64/kernel/perf_event.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/probes/kprobes.c  kernel_platform/common/arch/arm64/kernel/probes/kprobes.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/setup.c  kernel_platform/common/arch/arm64/kernel/setup.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/suspend.c  kernel_platform/common/arch/arm64/kernel/suspend.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/syscall.c  kernel_platform/common/arch/arm64/kernel/syscall.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/vmlinux.lds.S  kernel_platform/common/arch/arm64/kernel/vmlinux.lds.S 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/mm/fault.c  kernel_platform/common/arch/arm64/mm/fault.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/mm/mmu.c  kernel_platform/common/arch/arm64/mm/mmu.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/mm/pgd.c  kernel_platform/common/arch/arm64/mm/pgd.c 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/mm/proc.S  kernel_platform/common/arch/arm64/mm/proc.S 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/net/bpf_jit_comp.c  kernel_platform/common/arch/arm64/net/bpf_jit_comp.c 
cp /home/user/UltraS23/kernel_platform/common/arch/csky/include/asm/processor.h  kernel_platform/common/arch/csky/include/asm/processor.h 
cp /home/user/UltraS23/kernel_platform/common/arch/um/include/asm/common.lds.S  kernel_platform/common/arch/um/include/asm/common.lds.S 
cp /home/user/UltraS23/kernel_platform/common/arch/um/include/asm/io.h  kernel_platform/common/arch/um/include/asm/io.h 
cp /home/user/UltraS23/kernel_platform/common/arch/x86/include/asm/kvm_host.h  kernel_platform/common/arch/x86/include/asm/kvm_host.h 
cp /home/user/UltraS23/kernel_platform/common/arch/x86/kvm/mmu/mmu.c  kernel_platform/common/arch/x86/kvm/mmu/mmu.c 
cp /home/user/UltraS23/kernel_platform/common/arch/x86/kvm/svm/svm.c  kernel_platform/common/arch/x86/kvm/svm/svm.c 
cp /home/user/UltraS23/kernel_platform/common/arch/x86/kvm/vmx/vmx.c  kernel_platform/common/arch/x86/kvm/vmx/vmx.c 
cp /home/user/UltraS23/kernel_platform/common/arch/x86/kvm/x86.c  kernel_platform/common/arch/x86/kvm/x86.c 
cp /home/user/UltraS23/kernel_platform/common/block/bio.c  kernel_platform/common/block/bio.c 
cp /home/user/UltraS23/kernel_platform/common/block/blk-mq.c  kernel_platform/common/block/blk-mq.c 
cp /home/user/UltraS23/kernel_platform/common/block/genhd.c  kernel_platform/common/block/genhd.c 
cp /home/user/UltraS23/kernel_platform/common/block/ioctl.c  kernel_platform/common/block/ioctl.c 
cp /home/user/UltraS23/kernel_platform/common/crypto/api.c  kernel_platform/common/crypto/api.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/android/binder.c  kernel_platform/common/drivers/android/binder.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/android/binder_alloc.c  kernel_platform/common/drivers/android/binder_alloc.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/android/binder_internal.h  kernel_platform/common/drivers/android/binder_internal.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/android/binderfs.c  kernel_platform/common/drivers/android/binderfs.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/android/vendor_hooks.c  kernel_platform/common/drivers/android/vendor_hooks.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/base/arch_topology.c  kernel_platform/common/drivers/base/arch_topology.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/base/core.c  kernel_platform/common/drivers/base/core.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/base/power/runtime.c  kernel_platform/common/drivers/base/power/runtime.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/base/power/wakeup.c  kernel_platform/common/drivers/base/power/wakeup.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/block/loop.c  kernel_platform/common/drivers/block/loop.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/block/zram/zcomp.c  kernel_platform/common/drivers/block/zram/zcomp.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/block/zram/zcomp.h  kernel_platform/common/drivers/block/zram/zcomp.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/block/zram/zram_drv.c  kernel_platform/common/drivers/block/zram/zram_drv.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/block/zram/zram_drv.h  kernel_platform/common/drivers/block/zram/zram_drv.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/connector/cn_proc.c  kernel_platform/common/drivers/connector/cn_proc.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/cpufreq/cpufreq.c  kernel_platform/common/drivers/cpufreq/cpufreq.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/dma-buf/dma-buf.c  kernel_platform/common/drivers/dma-buf/dma-buf.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/dma-buf/dma-heap.c  kernel_platform/common/drivers/dma-buf/dma-heap.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/firmware/smccc/kvm_guest.c  kernel_platform/common/drivers/firmware/smccc/kvm_guest.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/hid-apple.c  kernel_platform/common/drivers/hid/hid-apple.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/hid-ids.h  kernel_platform/common/drivers/hid/hid-ids.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/hid-input.c  kernel_platform/common/drivers/hid/hid-input.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/hid-logitech-hidpp.c  kernel_platform/common/drivers/hid/hid-logitech-hidpp.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/hid-quirks.c  kernel_platform/common/drivers/hid/hid-quirks.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/hid-samsung.c  kernel_platform/common/drivers/hid/hid-samsung.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/uhid.c  kernel_platform/common/drivers/hid/uhid.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/usbhid/hid-core.c  kernel_platform/common/drivers/hid/usbhid/hid-core.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/hid/usbhid/usbhid.h  kernel_platform/common/drivers/hid/usbhid/usbhid.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/input/evdev.c  kernel_platform/common/drivers/input/evdev.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/iommu/arm/arm-smmu/arm-smmu.c  kernel_platform/common/drivers/iommu/arm/arm-smmu/arm-smmu.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/iommu/iommu.c  kernel_platform/common/drivers/iommu/iommu.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/md/bcache/bcache.h  kernel_platform/common/drivers/md/bcache/bcache.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/md/bcache/bset.h  kernel_platform/common/drivers/md/bcache/bset.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/md/bcache/features.c  kernel_platform/common/drivers/md/bcache/features.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/md/bcache/features.h  kernel_platform/common/drivers/md/bcache/features.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/md/dm-verity-target.c  kernel_platform/common/drivers/md/dm-verity-target.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/mmc/core/mmc.c  kernel_platform/common/drivers/mmc/core/mmc.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/mmc/core/sd.c  kernel_platform/common/drivers/mmc/core/sd.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/net/tun.c  kernel_platform/common/drivers/net/tun.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/net/wireless/mac80211_hwsim.c  kernel_platform/common/drivers/net/wireless/mac80211_hwsim.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/of/fdt.c  kernel_platform/common/drivers/of/fdt.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/of/of_reserved_mem.c  kernel_platform/common/drivers/of/of_reserved_mem.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/pci/controller/dwc/pcie-designware-host.c  kernel_platform/common/drivers/pci/controller/dwc/pcie-designware-host.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/pci/controller/dwc/pcie-designware.h  kernel_platform/common/drivers/pci/controller/dwc/pcie-designware.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/phy/phy-core.c  kernel_platform/common/drivers/phy/phy-core.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/rtc/class.c  kernel_platform/common/drivers/rtc/class.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/scsi/sd.c  kernel_platform/common/drivers/scsi/sd.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/scsi/ufs/ufshcd-crypto.c  kernel_platform/common/drivers/scsi/ufs/ufshcd-crypto.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/scsi/ufs/ufshcd.c  kernel_platform/common/drivers/scsi/ufs/ufshcd.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/scsi/ufs/ufshci.h  kernel_platform/common/drivers/scsi/ufs/ufshci.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/thermal/thermal_core.c  kernel_platform/common/drivers/thermal/thermal_core.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/tty/sysrq.c  kernel_platform/common/drivers/tty/sysrq.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/core/devio.c  kernel_platform/common/drivers/usb/core/devio.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/core/driver.c  kernel_platform/common/drivers/usb/core/driver.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/core/hub.c  kernel_platform/common/drivers/usb/core/hub.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/core/quirks.c  kernel_platform/common/drivers/usb/core/quirks.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/core/usb.h  kernel_platform/common/drivers/usb/core/usb.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/dwc3/gadget.c  kernel_platform/common/drivers/usb/dwc3/gadget.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/gadget/composite.c  kernel_platform/common/drivers/usb/gadget/composite.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/gadget/configfs.c  kernel_platform/common/drivers/usb/gadget/configfs.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/gadget/function/f_accessory.c  kernel_platform/common/drivers/usb/gadget/function/f_accessory.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/gadget/function/f_acm.c  kernel_platform/common/drivers/usb/gadget/function/f_acm.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/gadget/function/f_mass_storage.c  kernel_platform/common/drivers/usb/gadget/function/f_mass_storage.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/gadget/function/f_uac2.c  kernel_platform/common/drivers/usb/gadget/function/f_uac2.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/gadget/function/u_serial.c  kernel_platform/common/drivers/usb/gadget/function/u_serial.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/host/xhci-mem.c  kernel_platform/common/drivers/usb/host/xhci-mem.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/host/xhci-plat.c  kernel_platform/common/drivers/usb/host/xhci-plat.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/storage/debug.h  kernel_platform/common/drivers/usb/storage/debug.h 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/storage/scsiglue.c  kernel_platform/common/drivers/usb/storage/scsiglue.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/storage/transport.c  kernel_platform/common/drivers/usb/storage/transport.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/storage/usb.c  kernel_platform/common/drivers/usb/storage/usb.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/video/fbdev/core/fbcon.c  kernel_platform/common/drivers/video/fbdev/core/fbcon.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/video/fbdev/core/fbmem.c  kernel_platform/common/drivers/video/fbdev/core/fbmem.c 
cp /home/user/UltraS23/kernel_platform/common/drivers/video/fbdev/pxa3xx-gcu.c  kernel_platform/common/drivers/video/fbdev/pxa3xx-gcu.c 
cp /home/user/UltraS23/kernel_platform/common/fs/attr.c  kernel_platform/common/fs/attr.c 
cp /home/user/UltraS23/kernel_platform/common/fs/crypto/crypto.c  kernel_platform/common/fs/crypto/crypto.c 
cp /home/user/UltraS23/kernel_platform/common/fs/crypto/fscrypt_private.h  kernel_platform/common/fs/crypto/fscrypt_private.h 
cp /home/user/UltraS23/kernel_platform/common/fs/crypto/keysetup.c  kernel_platform/common/fs/crypto/keysetup.c 
cp /home/user/UltraS23/kernel_platform/common/fs/crypto/policy.c  kernel_platform/common/fs/crypto/policy.c 
cp /home/user/UltraS23/kernel_platform/common/fs/d_path.c  kernel_platform/common/fs/d_path.c 
cp /home/user/UltraS23/kernel_platform/common/fs/erofs/internal.h  kernel_platform/common/fs/erofs/internal.h 
cp /home/user/UltraS23/kernel_platform/common/fs/erofs/super.c  kernel_platform/common/fs/erofs/super.c 
cp /home/user/UltraS23/kernel_platform/common/fs/erofs/zdata.c  kernel_platform/common/fs/erofs/zdata.c 
cp /home/user/UltraS23/kernel_platform/common/fs/erofs/zdata.h  kernel_platform/common/fs/erofs/zdata.h 
cp /home/user/UltraS23/kernel_platform/common/fs/exec.c  kernel_platform/common/fs/exec.c 
cp /home/user/UltraS23/kernel_platform/common/fs/exfat/fatent.c  kernel_platform/common/fs/exfat/fatent.c 
cp /home/user/UltraS23/kernel_platform/common/fs/ext4/super.c  kernel_platform/common/fs/ext4/super.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/checkpoint.c  kernel_platform/common/fs/f2fs/checkpoint.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/compress.c  kernel_platform/common/fs/f2fs/compress.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/data.c  kernel_platform/common/fs/f2fs/data.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/dir.c  kernel_platform/common/fs/f2fs/dir.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/f2fs.h  kernel_platform/common/fs/f2fs/f2fs.h 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/file.c  kernel_platform/common/fs/f2fs/file.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/gc.c  kernel_platform/common/fs/f2fs/gc.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/inode.c  kernel_platform/common/fs/f2fs/inode.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/namei.c  kernel_platform/common/fs/f2fs/namei.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/node.c  kernel_platform/common/fs/f2fs/node.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/segment.c  kernel_platform/common/fs/f2fs/segment.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/segment.h  kernel_platform/common/fs/f2fs/segment.h 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/super.c  kernel_platform/common/fs/f2fs/super.c 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/sysfs.c  kernel_platform/common/fs/f2fs/sysfs.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fat/fat.h  kernel_platform/common/fs/fat/fat.h 
cp /home/user/UltraS23/kernel_platform/common/fs/fat/inode.c  kernel_platform/common/fs/fat/inode.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fat/misc.c  kernel_platform/common/fs/fat/misc.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fcntl.c  kernel_platform/common/fs/fcntl.c 
cp /home/user/UltraS23/kernel_platform/common/fs/file_table.c  kernel_platform/common/fs/file_table.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fs-writeback.c  kernel_platform/common/fs/fs-writeback.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fuse/dev.c  kernel_platform/common/fs/fuse/dev.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fuse/dir.c  kernel_platform/common/fs/fuse/dir.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fuse/file.c  kernel_platform/common/fs/fuse/file.c 
cp /home/user/UltraS23/kernel_platform/common/fs/fuse/fuse_i.h  kernel_platform/common/fs/fuse/fuse_i.h 
cp /home/user/UltraS23/kernel_platform/common/fs/fuse/inode.c  kernel_platform/common/fs/fuse/inode.c 
cp /home/user/UltraS23/kernel_platform/common/fs/internal.h  kernel_platform/common/fs/internal.h 
cp /home/user/UltraS23/kernel_platform/common/fs/iomap/buffered-io.c  kernel_platform/common/fs/iomap/buffered-io.c 
cp /home/user/UltraS23/kernel_platform/common/fs/mount.h  kernel_platform/common/fs/mount.h 
cp /home/user/UltraS23/kernel_platform/common/fs/mpage.c  kernel_platform/common/fs/mpage.c 
cp /home/user/UltraS23/kernel_platform/common/fs/namei.c  kernel_platform/common/fs/namei.c 
cp /home/user/UltraS23/kernel_platform/common/fs/namespace.c  kernel_platform/common/fs/namespace.c 
cp /home/user/UltraS23/kernel_platform/common/fs/open.c  kernel_platform/common/fs/open.c 
cp /home/user/UltraS23/kernel_platform/common/fs/overlayfs/super.c  kernel_platform/common/fs/overlayfs/super.c 
cp /home/user/UltraS23/kernel_platform/common/fs/pnode.c  kernel_platform/common/fs/pnode.c 
cp /home/user/UltraS23/kernel_platform/common/fs/pnode.h  kernel_platform/common/fs/pnode.h 
cp /home/user/UltraS23/kernel_platform/common/fs/proc/base.c  kernel_platform/common/fs/proc/base.c 
cp /home/user/UltraS23/kernel_platform/common/fs/proc/internal.h  kernel_platform/common/fs/proc/internal.h 
cp /home/user/UltraS23/kernel_platform/common/fs/proc/meminfo.c  kernel_platform/common/fs/proc/meminfo.c 
cp /home/user/UltraS23/kernel_platform/common/fs/proc/task_mmu.c  kernel_platform/common/fs/proc/task_mmu.c 
cp /home/user/UltraS23/kernel_platform/common/fs/read_write.c  kernel_platform/common/fs/read_write.c 
cp /home/user/UltraS23/kernel_platform/common/fs/super.c  kernel_platform/common/fs/super.c 
cp /home/user/UltraS23/kernel_platform/common/fs/timerfd.c  kernel_platform/common/fs/timerfd.c 
cp /home/user/UltraS23/kernel_platform/common/include/asm-generic/vmlinux.lds.h  kernel_platform/common/include/asm-generic/vmlinux.lds.h 
cp /home/user/UltraS23/kernel_platform/common/include/crypto/hash.h  kernel_platform/common/include/crypto/hash.h 
cp /home/user/UltraS23/kernel_platform/common/include/dt-bindings/input/linux-event-codes.h  kernel_platform/common/include/dt-bindings/input/linux-event-codes.h 
cp /home/user/UltraS23/kernel_platform/common/include/kunit/test.h  kernel_platform/common/include/kunit/test.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/backing-dev-defs.h  kernel_platform/common/include/linux/backing-dev-defs.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/backing-dev.h  kernel_platform/common/include/linux/backing-dev.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/bio.h  kernel_platform/common/include/linux/bio.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/cleancache.h  kernel_platform/common/include/linux/cleancache.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/cred.h  kernel_platform/common/include/linux/cred.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/delayacct.h  kernel_platform/common/include/linux/delayacct.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/export.h  kernel_platform/common/include/linux/export.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/f2fs_fs.h  kernel_platform/common/include/linux/f2fs_fs.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/fbcon.h  kernel_platform/common/include/linux/fbcon.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/freezer.h  kernel_platform/common/include/linux/freezer.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/fs.h  kernel_platform/common/include/linux/fs.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/fscrypt.h  kernel_platform/common/include/linux/fscrypt.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/gfp.h  kernel_platform/common/include/linux/gfp.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/highmem.h  kernel_platform/common/include/linux/highmem.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/init_task.h  kernel_platform/common/include/linux/init_task.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/iommu.h  kernel_platform/common/include/linux/iommu.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/jump_label.h  kernel_platform/common/include/linux/jump_label.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/kasan.h  kernel_platform/common/include/linux/kasan.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/khugepaged.h  kernel_platform/common/include/linux/khugepaged.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/memblock.h  kernel_platform/common/include/linux/memblock.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/memcontrol.h  kernel_platform/common/include/linux/memcontrol.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/mm.h  kernel_platform/common/include/linux/mm.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/mm_inline.h  kernel_platform/common/include/linux/mm_inline.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/mount.h  kernel_platform/common/include/linux/mount.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/notifier.h  kernel_platform/common/include/linux/notifier.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/pagemap.h  kernel_platform/common/include/linux/pagemap.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/printk.h  kernel_platform/common/include/linux/printk.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/psi_types.h  kernel_platform/common/include/linux/psi_types.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/rmap.h  kernel_platform/common/include/linux/rmap.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/sched.h  kernel_platform/common/include/linux/sched.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/security.h  kernel_platform/common/include/linux/security.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/slab.h  kernel_platform/common/include/linux/slab.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/swap.h  kernel_platform/common/include/linux/swap.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/usb.h  kernel_platform/common/include/linux/usb.h 
cp /home/user/UltraS23/kernel_platform/common/include/linux/vmstat.h  kernel_platform/common/include/linux/vmstat.h 
cp /home/user/UltraS23/kernel_platform/common/include/net/bluetooth/l2cap.h  kernel_platform/common/include/net/bluetooth/l2cap.h 
cp /home/user/UltraS23/kernel_platform/common/include/net/cfg80211.h  kernel_platform/common/include/net/cfg80211.h 
cp /home/user/UltraS23/kernel_platform/common/include/net/netfilter/nf_conntrack.h  kernel_platform/common/include/net/netfilter/nf_conntrack.h 
cp /home/user/UltraS23/kernel_platform/common/include/net/sock.h  kernel_platform/common/include/net/sock.h 
cp /home/user/UltraS23/kernel_platform/common/include/scsi/scsi_host.h  kernel_platform/common/include/scsi/scsi_host.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/events/android_fs.h  kernel_platform/common/include/trace/events/android_fs.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/events/android_fs_template.h  kernel_platform/common/include/trace/events/android_fs_template.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/events/mmflags.h  kernel_platform/common/include/trace/events/mmflags.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/binder.h  kernel_platform/common/include/trace/hooks/binder.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/cgroup.h  kernel_platform/common/include/trace/hooks/cgroup.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/mm.h  kernel_platform/common/include/trace/hooks/mm.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/mmc.h  kernel_platform/common/include/trace/hooks/mmc.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/power.h  kernel_platform/common/include/trace/hooks/power.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/sched.h  kernel_platform/common/include/trace/hooks/sched.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/ufshcd.h  kernel_platform/common/include/trace/hooks/ufshcd.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/usb.h  kernel_platform/common/include/trace/hooks/usb.h 
cp /home/user/UltraS23/kernel_platform/common/include/trace/hooks/vmscan.h  kernel_platform/common/include/trace/hooks/vmscan.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/asm-generic/mman-common.h  kernel_platform/common/include/uapi/asm-generic/mman-common.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/asm-generic/socket.h  kernel_platform/common/include/uapi/asm-generic/socket.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/linux/f2fs.h  kernel_platform/common/include/uapi/linux/f2fs.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/linux/fs.h  kernel_platform/common/include/uapi/linux/fs.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/linux/if_tun.h  kernel_platform/common/include/uapi/linux/if_tun.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/linux/input-event-codes.h  kernel_platform/common/include/uapi/linux/input-event-codes.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/linux/magic.h  kernel_platform/common/include/uapi/linux/magic.h 
cp /home/user/UltraS23/kernel_platform/common/include/uapi/linux/netlink.h  kernel_platform/common/include/uapi/linux/netlink.h 
cp /home/user/UltraS23/kernel_platform/common/init/do_mounts_initrd.c  kernel_platform/common/init/do_mounts_initrd.c 
cp /home/user/UltraS23/kernel_platform/common/init/init_task.c  kernel_platform/common/init/init_task.c 
cp /home/user/UltraS23/kernel_platform/common/init/main.c  kernel_platform/common/init/main.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/audit.c  kernel_platform/common/kernel/audit.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/bpf/bpf_lru_list.h  kernel_platform/common/kernel/bpf/bpf_lru_list.h 
cp /home/user/UltraS23/kernel_platform/common/kernel/bpf/core.c  kernel_platform/common/kernel/bpf/core.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/cfi.c  kernel_platform/common/kernel/cfi.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/cgroup/cgroup-v1.c  kernel_platform/common/kernel/cgroup/cgroup-v1.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/cgroup/cgroup.c  kernel_platform/common/kernel/cgroup/cgroup.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/cgroup/cpuset.c  kernel_platform/common/kernel/cgroup/cpuset.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/cgroup/legacy_freezer.c  kernel_platform/common/kernel/cgroup/legacy_freezer.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/cred.c  kernel_platform/common/kernel/cred.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/delayacct.c  kernel_platform/common/kernel/delayacct.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/dma/contiguous.c  kernel_platform/common/kernel/dma/contiguous.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/exit.c  kernel_platform/common/kernel/exit.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/fork.c  kernel_platform/common/kernel/fork.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/freezer.c  kernel_platform/common/kernel/freezer.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/gen_kheaders.sh  kernel_platform/common/kernel/gen_kheaders.sh 
cp /home/user/UltraS23/kernel_platform/common/kernel/locking/rwsem.c  kernel_platform/common/kernel/locking/rwsem.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/module.c  kernel_platform/common/kernel/module.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/power/main.c  kernel_platform/common/kernel/power/main.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/power/process.c  kernel_platform/common/kernel/power/process.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/power/suspend.c  kernel_platform/common/kernel/power/suspend.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/printk/printk.c  kernel_platform/common/kernel/printk/printk.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/ptrace.c  kernel_platform/common/kernel/ptrace.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/rcu/rcu.h  kernel_platform/common/kernel/rcu/rcu.h 
cp /home/user/UltraS23/kernel_platform/common/kernel/rcu/srcutiny.c  kernel_platform/common/kernel/rcu/srcutiny.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/rcu/srcutree.c  kernel_platform/common/kernel/rcu/srcutree.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/rcu/tasks.h  kernel_platform/common/kernel/rcu/tasks.h 
cp /home/user/UltraS23/kernel_platform/common/kernel/rcu/tiny.c  kernel_platform/common/kernel/rcu/tiny.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/rcu/tree.c  kernel_platform/common/kernel/rcu/tree.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/rcu/update.c  kernel_platform/common/kernel/rcu/update.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/reboot.c  kernel_platform/common/kernel/reboot.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sched/core.c  kernel_platform/common/kernel/sched/core.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sched/cpufreq.c  kernel_platform/common/kernel/sched/cpufreq.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sched/fair.c  kernel_platform/common/kernel/sched/fair.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sched/pelt.c  kernel_platform/common/kernel/sched/pelt.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sched/psi.c  kernel_platform/common/kernel/sched/psi.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sched/rt.c  kernel_platform/common/kernel/sched/rt.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/signal.c  kernel_platform/common/kernel/signal.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sys.c  kernel_platform/common/kernel/sys.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/sysctl.c  kernel_platform/common/kernel/sysctl.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/time/alarmtimer.c  kernel_platform/common/kernel/time/alarmtimer.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/time/sched_clock.c  kernel_platform/common/kernel/time/sched_clock.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/time/timekeeping_debug.c  kernel_platform/common/kernel/time/timekeeping_debug.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/trace/trace.c  kernel_platform/common/kernel/trace/trace.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/trace/trace_output.c  kernel_platform/common/kernel/trace/trace_output.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/umh.c  kernel_platform/common/kernel/umh.c 
cp /home/user/UltraS23/kernel_platform/common/kernel/user.c  kernel_platform/common/kernel/user.c 
cp /home/user/UltraS23/kernel_platform/common/lib/kunit/executor.c  kernel_platform/common/lib/kunit/executor.c 
cp /home/user/UltraS23/kernel_platform/common/lib/kunit/kunit-example-test.c  kernel_platform/common/lib/kunit/kunit-example-test.c 
cp /home/user/UltraS23/kernel_platform/common/lib/kunit/string-stream-test.c  kernel_platform/common/lib/kunit/string-stream-test.c 
cp /home/user/UltraS23/kernel_platform/common/lib/kunit/string-stream.c  kernel_platform/common/lib/kunit/string-stream.c 
cp /home/user/UltraS23/kernel_platform/common/lib/kunit/test.c  kernel_platform/common/lib/kunit/test.c 
cp /home/user/UltraS23/kernel_platform/common/lib/show_mem.c  kernel_platform/common/lib/show_mem.c 
cp /home/user/UltraS23/kernel_platform/common/mm/backing-dev.c  kernel_platform/common/mm/backing-dev.c 
cp /home/user/UltraS23/kernel_platform/common/mm/cleancache.c  kernel_platform/common/mm/cleancache.c 
cp /home/user/UltraS23/kernel_platform/common/mm/cma.c  kernel_platform/common/mm/cma.c 
cp /home/user/UltraS23/kernel_platform/common/mm/compaction.c  kernel_platform/common/mm/compaction.c 
cp /home/user/UltraS23/kernel_platform/common/mm/filemap.c  kernel_platform/common/mm/filemap.c 
cp /home/user/UltraS23/kernel_platform/common/mm/huge_memory.c  kernel_platform/common/mm/huge_memory.c 
cp /home/user/UltraS23/kernel_platform/common/mm/internal.h  kernel_platform/common/mm/internal.h 
cp /home/user/UltraS23/kernel_platform/common/mm/ksm.c  kernel_platform/common/mm/ksm.c 
cp /home/user/UltraS23/kernel_platform/common/mm/madvise.c  kernel_platform/common/mm/madvise.c 
cp /home/user/UltraS23/kernel_platform/common/mm/memblock.c  kernel_platform/common/mm/memblock.c 
cp /home/user/UltraS23/kernel_platform/common/mm/memcontrol.c  kernel_platform/common/mm/memcontrol.c 
cp /home/user/UltraS23/kernel_platform/common/mm/memory-failure.c  kernel_platform/common/mm/memory-failure.c 
cp /home/user/UltraS23/kernel_platform/common/mm/memory.c  kernel_platform/common/mm/memory.c 
cp /home/user/UltraS23/kernel_platform/common/mm/migrate.c  kernel_platform/common/mm/migrate.c 
cp /home/user/UltraS23/kernel_platform/common/mm/mmap.c  kernel_platform/common/mm/mmap.c 
cp /home/user/UltraS23/kernel_platform/common/mm/page-writeback.c  kernel_platform/common/mm/page-writeback.c 
cp /home/user/UltraS23/kernel_platform/common/mm/page_alloc.c  kernel_platform/common/mm/page_alloc.c 
cp /home/user/UltraS23/kernel_platform/common/mm/page_idle.c  kernel_platform/common/mm/page_idle.c 
cp /home/user/UltraS23/kernel_platform/common/mm/page_io.c  kernel_platform/common/mm/page_io.c 
cp /home/user/UltraS23/kernel_platform/common/mm/process_vm_access.c  kernel_platform/common/mm/process_vm_access.c 
cp /home/user/UltraS23/kernel_platform/common/mm/rmap.c  kernel_platform/common/mm/rmap.c 
cp /home/user/UltraS23/kernel_platform/common/mm/shmem.c  kernel_platform/common/mm/shmem.c 
cp /home/user/UltraS23/kernel_platform/common/mm/slab.c  kernel_platform/common/mm/slab.c 
cp /home/user/UltraS23/kernel_platform/common/mm/slab.h  kernel_platform/common/mm/slab.h 
cp /home/user/UltraS23/kernel_platform/common/mm/slab_common.c  kernel_platform/common/mm/slab_common.c 
cp /home/user/UltraS23/kernel_platform/common/mm/slob.c  kernel_platform/common/mm/slob.c 
cp /home/user/UltraS23/kernel_platform/common/mm/slub.c  kernel_platform/common/mm/slub.c 
cp /home/user/UltraS23/kernel_platform/common/mm/swap.c  kernel_platform/common/mm/swap.c 
cp /home/user/UltraS23/kernel_platform/common/mm/swapfile.c  kernel_platform/common/mm/swapfile.c 
cp /home/user/UltraS23/kernel_platform/common/mm/vmalloc.c  kernel_platform/common/mm/vmalloc.c 
cp /home/user/UltraS23/kernel_platform/common/mm/vmscan.c  kernel_platform/common/mm/vmscan.c 
cp /home/user/UltraS23/kernel_platform/common/mm/vmstat.c  kernel_platform/common/mm/vmstat.c 
cp /home/user/UltraS23/kernel_platform/common/mm/zsmalloc.c  kernel_platform/common/mm/zsmalloc.c 
cp /home/user/UltraS23/kernel_platform/common/mm/zswap.c  kernel_platform/common/mm/zswap.c 
cp /home/user/UltraS23/kernel_platform/common/net/bluetooth/hci_sock.c  kernel_platform/common/net/bluetooth/hci_sock.c 
cp /home/user/UltraS23/kernel_platform/common/net/bluetooth/l2cap_core.c  kernel_platform/common/net/bluetooth/l2cap_core.c 
cp /home/user/UltraS23/kernel_platform/common/net/core/neighbour.c  kernel_platform/common/net/core/neighbour.c 
cp /home/user/UltraS23/kernel_platform/common/net/core/sock.c  kernel_platform/common/net/core/sock.c 
cp /home/user/UltraS23/kernel_platform/common/net/ipv4/udp.c  kernel_platform/common/net/ipv4/udp.c 
cp /home/user/UltraS23/kernel_platform/common/net/ipv6/addrconf.c  kernel_platform/common/net/ipv6/addrconf.c 
cp /home/user/UltraS23/kernel_platform/common/net/ipv6/ndisc.c  kernel_platform/common/net/ipv6/ndisc.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/agg-rx.c  kernel_platform/common/net/mac80211/agg-rx.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/cfg.c  kernel_platform/common/net/mac80211/cfg.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/ibss.c  kernel_platform/common/net/mac80211/ibss.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/ieee80211_i.h  kernel_platform/common/net/mac80211/ieee80211_i.h 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/mesh.c  kernel_platform/common/net/mac80211/mesh.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/mesh_hwmp.c  kernel_platform/common/net/mac80211/mesh_hwmp.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/mesh_plink.c  kernel_platform/common/net/mac80211/mesh_plink.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/mesh_sync.c  kernel_platform/common/net/mac80211/mesh_sync.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/mlme.c  kernel_platform/common/net/mac80211/mlme.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/rx.c  kernel_platform/common/net/mac80211/rx.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/scan.c  kernel_platform/common/net/mac80211/scan.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/tdls.c  kernel_platform/common/net/mac80211/tdls.c 
cp /home/user/UltraS23/kernel_platform/common/net/mac80211/util.c  kernel_platform/common/net/mac80211/util.c 
cp /home/user/UltraS23/kernel_platform/common/net/netfilter/nf_conntrack_core.c  kernel_platform/common/net/netfilter/nf_conntrack_core.c 
cp /home/user/UltraS23/kernel_platform/common/net/netfilter/xt_connmark.c  kernel_platform/common/net/netfilter/xt_connmark.c 
cp /home/user/UltraS23/kernel_platform/common/net/wireless/nl80211.c  kernel_platform/common/net/wireless/nl80211.c 
cp /home/user/UltraS23/kernel_platform/common/net/wireless/reg.c  kernel_platform/common/net/wireless/reg.c 
cp /home/user/UltraS23/kernel_platform/common/net/wireless/scan.c  kernel_platform/common/net/wireless/scan.c 
cp /home/user/UltraS23/kernel_platform/common/net/wireless/sme.c  kernel_platform/common/net/wireless/sme.c 
cp /home/user/UltraS23/kernel_platform/common/net/wireless/trace.h  kernel_platform/common/net/wireless/trace.h 
cp /home/user/UltraS23/kernel_platform/common/net/wireless/wext-compat.c  kernel_platform/common/net/wireless/wext-compat.c 
cp /home/user/UltraS23/kernel_platform/common/scripts/checkpatch.pl  kernel_platform/common/scripts/checkpatch.pl 
cp /home/user/UltraS23/kernel_platform/common/scripts/dtc/include-prefixes/dt-bindings/input/linux-event-codes.h  kernel_platform/common/scripts/dtc/include-prefixes/dt-bindings/input/linux-event-codes.h 
cp /home/user/UltraS23/kernel_platform/common/scripts/gen_autoksyms.sh  kernel_platform/common/scripts/gen_autoksyms.sh 
cp /home/user/UltraS23/kernel_platform/common/scripts/link-vmlinux.sh  kernel_platform/common/scripts/link-vmlinux.sh 
cp /home/user/UltraS23/kernel_platform/common/security/integrity/iint.c  kernel_platform/common/security/integrity/iint.c 
cp /home/user/UltraS23/kernel_platform/common/security/integrity/integrity.h  kernel_platform/common/security/integrity/integrity.h 
cp /home/user/UltraS23/kernel_platform/common/security/security.c  kernel_platform/common/security/security.c 
cp /home/user/UltraS23/kernel_platform/common/security/selinux/hooks.c  kernel_platform/common/security/selinux/hooks.c 
cp /home/user/UltraS23/kernel_platform/common/security/selinux/include/objsec.h  kernel_platform/common/security/selinux/include/objsec.h 
cp /home/user/UltraS23/kernel_platform/common/sound/core/pcm_lib.c  kernel_platform/common/sound/core/pcm_lib.c 
cp /home/user/UltraS23/kernel_platform/common/sound/soc/soc-core.c  kernel_platform/common/sound/soc/soc-core.c 
cp /home/user/UltraS23/kernel_platform/common/sound/usb/card.c  kernel_platform/common/sound/usb/card.c 
cp /home/user/UltraS23/kernel_platform/common/sound/usb/quirks.c  kernel_platform/common/sound/usb/quirks.c 
cp /home/user/UltraS23/kernel_platform/common/tools/testing/kunit/kunit.py  kernel_platform/common/tools/testing/kunit/kunit.py 
cp /home/user/UltraS23/kernel_platform/common/tools/testing/kunit/kunit_config.py  kernel_platform/common/tools/testing/kunit/kunit_config.py 
cp /home/user/UltraS23/kernel_platform/common/tools/testing/kunit/kunit_kernel.py  kernel_platform/common/tools/testing/kunit/kunit_kernel.py 
