cp -r  	/home/user/UltraS23/kernel_platform/common/fs/dlog_hook.c	 kernel_platform/common/fs/dlog_hook.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/crypto/fscrypt_knox_private.h	 kernel_platform/common/fs/crypto/fscrypt_knox_private.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/crypto/ddar	 kernel_platform/common/fs/crypto/ddar
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/crypto/ddar/ddar_crypto.c	 kernel_platform/common/fs/crypto/ddar/ddar_crypto.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/crypto/ddar/ddar_crypto.h	 kernel_platform/common/fs/crypto/ddar/ddar_crypto.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/crypto/fscrypt_ddar.c	 kernel_platform/common/fs/crypto/fscrypt_ddar.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat	 kernel_platform/common/fs/sdfat
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/dfr.h	 kernel_platform/common/fs/sdfat/dfr.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/api.c	 kernel_platform/common/fs/sdfat/api.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/core.c	 kernel_platform/common/fs/sdfat/core.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/misc.c	 kernel_platform/common/fs/sdfat/misc.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/core_exfat.c	 kernel_platform/common/fs/sdfat/core_exfat.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/core_fat.c	 kernel_platform/common/fs/sdfat/core_fat.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/sdfat.c	 kernel_platform/common/fs/sdfat/sdfat.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/config.h	 kernel_platform/common/fs/sdfat/config.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/statistics.c	 kernel_platform/common/fs/sdfat/statistics.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/upcase.h	 kernel_platform/common/fs/sdfat/upcase.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/xattr.c	 kernel_platform/common/fs/sdfat/xattr.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/core.h	 kernel_platform/common/fs/sdfat/core.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/blkdev.c	 kernel_platform/common/fs/sdfat/blkdev.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/sdfat.h	 kernel_platform/common/fs/sdfat/sdfat.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/Kconfig	 kernel_platform/common/fs/sdfat/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/amap_smart.h	 kernel_platform/common/fs/sdfat/amap_smart.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/cache.c	 kernel_platform/common/fs/sdfat/cache.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/fatent.c	 kernel_platform/common/fs/sdfat/fatent.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/version.h	 kernel_platform/common/fs/sdfat/version.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/mpage.c	 kernel_platform/common/fs/sdfat/mpage.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/amap_smart.c	 kernel_platform/common/fs/sdfat/amap_smart.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/Makefile	 kernel_platform/common/fs/sdfat/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/dfr.c	 kernel_platform/common/fs/sdfat/dfr.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/api.h	 kernel_platform/common/fs/sdfat/api.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/extent.c	 kernel_platform/common/fs/sdfat/extent.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/sdfat_fs.h	 kernel_platform/common/fs/sdfat/sdfat_fs.h
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/sdfat/nls.c	 kernel_platform/common/fs/sdfat/nls.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/proc/proc_avc.c	 kernel_platform/common/fs/proc/proc_avc.c
cp -r  	/home/user/UltraS23/kernel_platform/common/fs/proc/fslog.c	 kernel_platform/common/fs/proc/fslog.c
cp -r  	/home/user/UltraS23/kernel_platform/common/net/netfilter/xt_domainfilter.c	 kernel_platform/common/net/netfilter/xt_domainfilter.c
cp -r  	/home/user/UltraS23/kernel_platform/common/net/ncm	 kernel_platform/common/net/ncm
cp -r  	/home/user/UltraS23/kernel_platform/common/net/ncm/ncm.c	 kernel_platform/common/net/ncm/ncm.c
cp -r  	/home/user/UltraS23/kernel_platform/common/net/ncm/Kconfig	 kernel_platform/common/net/ncm/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/net/ncm/Makefile	 kernel_platform/common/net/ncm/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/kzerod.c	 kernel_platform/common/mm/kzerod.c
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm	 kernel_platform/common/mm/sec_mm
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm/panic_handler.c	 kernel_platform/common/mm/sec_mm/panic_handler.c
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm/dump_tasks.c	 kernel_platform/common/mm/sec_mm/dump_tasks.c
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm/Kconfig	 kernel_platform/common/mm/sec_mm/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm/sec_mm.h	 kernel_platform/common/mm/sec_mm/sec_mm.h
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm/sec_mm_init.c	 kernel_platform/common/mm/sec_mm/sec_mm_init.c
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm/Makefile	 kernel_platform/common/mm/sec_mm/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/sec_mm/lowfile_detect.c	 kernel_platform/common/mm/sec_mm/lowfile_detect.c
cp -r  	/home/user/UltraS23/kernel_platform/common/mm/io_record.c	 kernel_platform/common/mm/io_record.c
cp -r  	/home/user/UltraS23/kernel_platform/common/arch/arm64/configs/consolidate.fragment	 kernel_platform/common/arch/arm64/configs/consolidate.fragment
cp -r  	/home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/uh_entry.S	 kernel_platform/common/arch/arm64/kernel/uh_entry.S
cp -r  	/home/user/UltraS23/kernel_platform/common/arch/um/include/asm/io-mock.h	 kernel_platform/common/arch/um/include/asm/io-mock.h
cp -r  	/home/user/UltraS23/kernel_platform/common/arch/um/include/asm/io-mock-shared.h	 kernel_platform/common/arch/um/include/asm/io-mock-shared.h
cp -r  	/home/user/UltraS23/kernel_platform/common/arch/um/kernel/io-mock.c	 kernel_platform/common/arch/um/kernel/io-mock.c
cp -r  	/home/user/UltraS23/kernel_platform/common/crypto/fips140_integrity.c	 kernel_platform/common/crypto/fips140_integrity.c
cp -r  	/home/user/UltraS23/kernel_platform/common/crypto/fips140_test.h	 kernel_platform/common/crypto/fips140_test.h
cp -r  	/home/user/UltraS23/kernel_platform/common/crypto/fips140_out.c	 kernel_platform/common/crypto/fips140_out.c
cp -r  	/home/user/UltraS23/kernel_platform/common/crypto/fips140_test_tv.h	 kernel_platform/common/crypto/fips140_test_tv.h
cp -r  	/home/user/UltraS23/kernel_platform/common/crypto/fips140_post.c	 kernel_platform/common/crypto/fips140_post.c
cp -r  	/home/user/UltraS23/kernel_platform/common/crypto/fips140.h	 kernel_platform/common/crypto/fips140.h
cp -r  	/home/user/UltraS23/kernel_platform/common/crypto/fips140_test.c	 kernel_platform/common/crypto/fips140_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/include/net/ncm.h	 kernel_platform/common/include/net/ncm.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/io_record.h	 kernel_platform/common/include/linux/io_record.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/input/input_booster.h	 kernel_platform/common/include/linux/input/input_booster.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/netfilter/xt_domainfilter.h	 kernel_platform/common/include/linux/netfilter/xt_domainfilter.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/freecess.h	 kernel_platform/common/include/linux/freecess.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/proca.h	 kernel_platform/common/include/linux/proca.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/platform_device_mock.h	 kernel_platform/common/include/linux/platform_device_mock.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/uh.h	 kernel_platform/common/include/linux/uh.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/dsms.h	 kernel_platform/common/include/linux/dsms.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/mz.h	 kernel_platform/common/include/linux/mz.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/proc_avc.h	 kernel_platform/common/include/linux/proc_avc.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/task_integrity.h	 kernel_platform/common/include/linux/task_integrity.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/hugepage_pool.h	 kernel_platform/common/include/linux/hugepage_pool.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/kasan-enabled.h	 kernel_platform/common/include/linux/kasan-enabled.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/kdp.h	 kernel_platform/common/include/linux/kdp.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/defex.h	 kernel_platform/common/include/linux/defex.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/fslog.h	 kernel_platform/common/include/linux/fslog.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/linux/rkp.h	 kernel_platform/common/include/linux/rkp.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/kunit/params.h	 kernel_platform/common/include/kunit/params.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/kunit/strerror.h	 kernel_platform/common/include/kunit/strerror.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/kunit/mock.h	 kernel_platform/common/include/kunit/mock.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/kunit/kunit-stream.h	 kernel_platform/common/include/kunit/kunit-stream.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/kunit/string-stream.h	 kernel_platform/common/include/kunit/string-stream.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar	 kernel_platform/common/include/ddar
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar/fs_request.h	 kernel_platform/common/include/ddar/fs_request.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar/dek_common.h	 kernel_platform/common/include/ddar/dek_common.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar/fs_handler.h	 kernel_platform/common/include/ddar/fs_handler.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar/common.h	 kernel_platform/common/include/ddar/common.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar/cache_cleanup.h	 kernel_platform/common/include/ddar/cache_cleanup.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar/dd_i.h	 kernel_platform/common/include/ddar/dd_i.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/ddar/dd.h	 kernel_platform/common/include/ddar/dd.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/uapi/linux/netfilter/xt_domainfilter.h	 kernel_platform/common/include/uapi/linux/netfilter/xt_domainfilter.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/trace/hooks/save_incpath.h	 kernel_platform/common/include/trace/hooks/save_incpath.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/trace/hooks/xhci.h	 kernel_platform/common/include/trace/hooks/xhci.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/trace/hooks/mz.h	 kernel_platform/common/include/trace/hooks/mz.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/trace/hooks/restore_incpath.h	 kernel_platform/common/include/trace/hooks/restore_incpath.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/trace/hooks/user.h	 kernel_platform/common/include/trace/hooks/user.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/trace/events/tracing_mark_write.h	 kernel_platform/common/include/trace/events/tracing_mark_write.h
cp -r  	/home/user/UltraS23/kernel_platform/common/include/trace/events/sec_gmr.h	 kernel_platform/common/include/trace/events/sec_gmr.h
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh	 kernel_platform/common/drivers/uh
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh/uh_debug_log.c	 kernel_platform/common/drivers/uh/uh_debug_log.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh/kdp.c	 kernel_platform/common/drivers/uh/kdp.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh/rkp_module_support.c	 kernel_platform/common/drivers/uh/rkp_module_support.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh/rkp_test.c	 kernel_platform/common/drivers/uh/rkp_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh/Makefile	 kernel_platform/common/drivers/uh/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh/rkp.c	 kernel_platform/common/drivers/uh/rkp.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/uh/kdp_test.c	 kernel_platform/common/drivers/uh/kdp_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/dma-buf/dma-heap-trace.c	 kernel_platform/common/drivers/dma-buf/dma-heap-trace.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/base/platform-mock.c	 kernel_platform/common/drivers/base/platform-mock.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/usb/core/usb_host_certify.c	 kernel_platform/common/drivers/usb/core/usb_host_certify.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/staging/android/freecess_pkg.c	 kernel_platform/common/drivers/staging/android/freecess_pkg.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/staging/android/lmkd_debug.c	 kernel_platform/common/drivers/staging/android/lmkd_debug.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/staging/android/freecess.c	 kernel_platform/common/drivers/staging/android/freecess.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/md/bcache/bcache_ondisk.h	 kernel_platform/common/drivers/md/bcache/bcache_ondisk.h
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/md/alta_bigdata.c	 kernel_platform/common/drivers/md/alta_bigdata.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/md/dm-verity-debug.c	 kernel_platform/common/drivers/md/dm-verity-debug.c
cp -r  	/home/user/UltraS23/kernel_platform/common/drivers/md/dm-verity-debug.h	 kernel_platform/common/drivers/md/dm-verity-debug.h
cp -r  	/home/user/UltraS23/kernel_platform/common/kunitconfigs	 kernel_platform/common/kunitconfigs
cp -r  	/home/user/UltraS23/kernel_platform/common/kunitconfigs/kunitconfig.kunit	 kernel_platform/common/kunitconfigs/kunitconfig.kunit
cp -r  	/home/user/UltraS23/kernel_platform/common/kunitconfigs/kunitconfig.gcov	 kernel_platform/common/kunitconfigs/kunitconfig.gcov
cp -r  	/home/user/UltraS23/kernel_platform/common/scripts/crypto	 kernel_platform/common/scripts/crypto
cp -r  	/home/user/UltraS23/kernel_platform/common/scripts/crypto/fips_crypto_integrity.py	 kernel_platform/common/scripts/crypto/fips_crypto_integrity.py
cp -r  	/home/user/UltraS23/kernel_platform/common/scripts/crypto/Utils.py	 kernel_platform/common/scripts/crypto/Utils.py
cp -r  	/home/user/UltraS23/kernel_platform/common/scripts/crypto/ELF.py	 kernel_platform/common/scripts/crypto/ELF.py
cp -r  	/home/user/UltraS23/kernel_platform/common/scripts/crypto/IntegrityRoutine.py	 kernel_platform/common/scripts/crypto/IntegrityRoutine.py
cp -r  	/home/user/UltraS23/kernel_platform/common/scripts/driver-dependencies.sh	 kernel_platform/common/scripts/driver-dependencies.sh
cp -r  	/home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_galaxy_presubmit	 kernel_platform/common/android/abi_gki_aarch64_galaxy_presubmit
cp -r  	/home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_sunxi	 kernel_platform/common/android/abi_gki_aarch64_sunxi
cp -r  	/home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_galaxy_grey	 kernel_platform/common/android/abi_gki_aarch64_galaxy_grey
cp -r  	/home/user/UltraS23/kernel_platform/common/android/abi_gki_aarch64_virtual_device_removed	 kernel_platform/common/android/abi_gki_aarch64_virtual_device_removed
cp -r  	/home/user/UltraS23/kernel_platform/common/build.config.gki_consolidate.aarch64	 kernel_platform/common/build.config.gki_consolidate.aarch64
cp -r  	/home/user/UltraS23/kernel_platform/common/lib/kunit/mock-test.c	 kernel_platform/common/lib/kunit/mock-test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/lib/kunit/kunit-stream.c	 kernel_platform/common/lib/kunit/kunit-stream.c
cp -r  	/home/user/UltraS23/kernel_platform/common/lib/kunit/strerror.c	 kernel_platform/common/lib/kunit/strerror.c
cp -r  	/home/user/UltraS23/kernel_platform/common/lib/kunit/common-mocks.c	 kernel_platform/common/lib/kunit/common-mocks.c
cp -r  	/home/user/UltraS23/kernel_platform/common/lib/kunit/mock.c	 kernel_platform/common/lib/kunit/mock.c
cp -r  	/home/user/UltraS23/kernel_platform/common/lib/kunit/strerror-test.c	 kernel_platform/common/lib/kunit/strerror-test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/lib/kunit/mock-macro-test.c	 kernel_platform/common/lib/kunit/mock-macro-test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar	 kernel_platform/common/security/ddar
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/dek_sysfs.c	 kernel_platform/common/security/ddar/dek_sysfs.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/cache_cleanup.c	 kernel_platform/common/security/ddar/cache_cleanup.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/dd_common.h	 kernel_platform/common/security/ddar/dd_common.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/dd_core.c	 kernel_platform/common/security/ddar/dd_core.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/dd_kernel_crypto.c	 kernel_platform/common/security/ddar/dd_kernel_crypto.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/fs_handler.c	 kernel_platform/common/security/ddar/fs_handler.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/dek.c	 kernel_platform/common/security/ddar/dek.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/Makefile	 kernel_platform/common/security/ddar/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/ddar/dd_xattr.c	 kernel_platform/common/security/ddar/dd_xattr.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung	 kernel_platform/common/security/samsung
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms	 kernel_platform/common/security/samsung/dsms
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_access_control.h	 kernel_platform/common/security/samsung/dsms/dsms_access_control.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_kernel_api.h	 kernel_platform/common/security/samsung/dsms/dsms_kernel_api.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_preboot_buffer.c	 kernel_platform/common/security/samsung/dsms/dsms_preboot_buffer.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_access_control.c	 kernel_platform/common/security/samsung/dsms/dsms_access_control.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_kernel_api.c	 kernel_platform/common/security/samsung/dsms/dsms_kernel_api.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_policy.c	 kernel_platform/common/security/samsung/dsms/dsms_policy.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_netlink.h	 kernel_platform/common/security/samsung/dsms/dsms_netlink.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_rate_limit.h	 kernel_platform/common/security/samsung/dsms/dsms_rate_limit.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test	 kernel_platform/common/security/samsung/dsms/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_init_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_init_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_netlink_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_netlink_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_policy_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_policy_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/dsms_test_utils.h	 kernel_platform/common/security/samsung/dsms/kunit_test/dsms_test_utils.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_rate_limit_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_rate_limit_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_test_utils_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_test_utils_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/dsms_test_utils.c	 kernel_platform/common/security/samsung/dsms/kunit_test/dsms_test_utils.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/Makefile	 kernel_platform/common/security/samsung/dsms/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_preboot_buffer_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_preboot_buffer_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_debug_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_debug_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_kernel_api_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_kernel_api_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_access_control_test.c	 kernel_platform/common/security/samsung/dsms/kunit_test/security_dsms_access_control_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_preboot_buffer.h	 kernel_platform/common/security/samsung/dsms/dsms_preboot_buffer.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/Kconfig	 kernel_platform/common/security/samsung/dsms/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_rate_limit.c	 kernel_platform/common/security/samsung/dsms/dsms_rate_limit.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_init.h	 kernel_platform/common/security/samsung/dsms/dsms_init.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_netlink_protocol.h	 kernel_platform/common/security/samsung/dsms/dsms_netlink_protocol.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/Makefile	 kernel_platform/common/security/samsung/dsms/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_test.h	 kernel_platform/common/security/samsung/dsms/dsms_test.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_init.c	 kernel_platform/common/security/samsung/dsms/dsms_init.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/dsms/dsms_netlink.c	 kernel_platform/common/security/samsung/dsms/dsms_netlink.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz_tee_driver	 kernel_platform/common/security/samsung/mz_tee_driver
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz_tee_driver/mz_tee_driver_teegris.c	 kernel_platform/common/security/samsung/mz_tee_driver/mz_tee_driver_teegris.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz_tee_driver/mz_tee_driver.c	 kernel_platform/common/security/samsung/mz_tee_driver/mz_tee_driver.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz_tee_driver/security_mz_tee_driver.py	 kernel_platform/common/security/samsung/mz_tee_driver/security_mz_tee_driver.py
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz_tee_driver/Kconfig	 kernel_platform/common/security/samsung/mz_tee_driver/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz_tee_driver/mz_tee_driver_qc.c	 kernel_platform/common/security/samsung/mz_tee_driver/mz_tee_driver_qc.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz_tee_driver/Makefile	 kernel_platform/common/security/samsung/mz_tee_driver/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five	 kernel_platform/common/security/samsung/five
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_hooks.c	 kernel_platform/common/security/samsung/five/five_hooks.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_cache.c	 kernel_platform/common/security/samsung/five/five_cache.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_cert.c	 kernel_platform/common/security/samsung/five/five_cert.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_pa.h	 kernel_platform/common/security/samsung/five/five_pa.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_crypto_comp.h	 kernel_platform/common/security/samsung/five/five_crypto_comp.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_testing.h	 kernel_platform/common/security/samsung/five/five_testing.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_porting.h	 kernel_platform/common/security/samsung/five/five_porting.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/task_integrity.c	 kernel_platform/common/security/samsung/five/task_integrity.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test	 kernel_platform/common/security/samsung/five/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_dmverity_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_dmverity_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_pa_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_pa_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_cache_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_cache_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_state_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_state_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/test_helpers.h	 kernel_platform/common/security/samsung/five/kunit_test/test_helpers.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_keyring_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_keyring_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_audit_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_audit_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_lv_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_lv_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/task_integrity_test.c	 kernel_platform/common/security/samsung/five/kunit_test/task_integrity_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_file.c	 kernel_platform/common/security/samsung/five/kunit_test/five_file.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_dsms_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_dsms_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_cert_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_cert_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_file.h	 kernel_platform/common/security/samsung/five/kunit_test/five_file.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/Makefile	 kernel_platform/common/security/samsung/five/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/kunit_test/five_crypto_test.c	 kernel_platform/common/security/samsung/five/kunit_test/five_crypto_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_main.c	 kernel_platform/common/security/samsung/five/five_main.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_dsms.h	 kernel_platform/common/security/samsung/five/five_dsms.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/Kconfig	 kernel_platform/common/security/samsung/five/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_dmverity.c	 kernel_platform/common/security/samsung/five/five_dmverity.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki	 kernel_platform/common/security/samsung/five/gki
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_hooks.c	 kernel_platform/common/security/samsung/five/gki/five_hooks.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_cache.c	 kernel_platform/common/security/samsung/five/gki/five_cache.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_tint_dev.c	 kernel_platform/common/security/samsung/five/gki/five_tint_dev.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/task_integrity.c	 kernel_platform/common/security/samsung/five/gki/task_integrity.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_iint.c	 kernel_platform/common/security/samsung/five/gki/five_iint.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_main.c	 kernel_platform/common/security/samsung/five/gki/five_main.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_vfs.h	 kernel_platform/common/security/samsung/five/gki/five_vfs.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_audit.h	 kernel_platform/common/security/samsung/five/gki/five_audit.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_state.c	 kernel_platform/common/security/samsung/five/gki/five_state.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_pa.c	 kernel_platform/common/security/samsung/five/gki/five_pa.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five.h	 kernel_platform/common/security/samsung/five/gki/five.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_iint.h	 kernel_platform/common/security/samsung/five/gki/five_iint.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_crypto.c	 kernel_platform/common/security/samsung/five/gki/five_crypto.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/task_integrity.h	 kernel_platform/common/security/samsung/five/gki/task_integrity.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_tee_interface.c	 kernel_platform/common/security/samsung/five/gki/five_tee_interface.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_appraise.c	 kernel_platform/common/security/samsung/five/gki/five_appraise.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_init.c	 kernel_platform/common/security/samsung/five/gki/five_init.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_tint_dev.h	 kernel_platform/common/security/samsung/five/gki/five_tint_dev.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_audit.c	 kernel_platform/common/security/samsung/five/gki/five_audit.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_vfs.c	 kernel_platform/common/security/samsung/five/gki/five_vfs.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_hooks.h	 kernel_platform/common/security/samsung/five/gki/five_hooks.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_cache.h	 kernel_platform/common/security/samsung/five/gki/five_cache.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/gki/five_tee_interface.h	 kernel_platform/common/security/samsung/five/gki/five_tee_interface.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_audit.h	 kernel_platform/common/security/samsung/five/five_audit.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_state.c	 kernel_platform/common/security/samsung/five/five_state.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_crypto.h	 kernel_platform/common/security/samsung/five/five_crypto.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_pa.c	 kernel_platform/common/security/samsung/five/five_pa.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_state.h	 kernel_platform/common/security/samsung/five/five_state.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_cert_builtin.S	 kernel_platform/common/security/samsung/five/five_cert_builtin.S
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_tee_api.h	 kernel_platform/common/security/samsung/five/five_tee_api.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five.h	 kernel_platform/common/security/samsung/five/five.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_crypto.c	 kernel_platform/common/security/samsung/five/five_crypto.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_tee_interface.c	 kernel_platform/common/security/samsung/five/five_tee_interface.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_appraise.c	 kernel_platform/common/security/samsung/five/five_appraise.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_init.c	 kernel_platform/common/security/samsung/five/five_init.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/Makefile	 kernel_platform/common/security/samsung/five/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_audit.c	 kernel_platform/common/security/samsung/five/five_audit.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/s_os	 kernel_platform/common/security/samsung/five/s_os
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/s_os/five_main.c	 kernel_platform/common/security/samsung/five/s_os/five_main.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/s_os/five_appraise.c	 kernel_platform/common/security/samsung/five/s_os/five_appraise.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_hooks.h	 kernel_platform/common/security/samsung/five/five_hooks.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_dmverity.h	 kernel_platform/common/security/samsung/five/five_dmverity.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_lv.h	 kernel_platform/common/security/samsung/five/five_lv.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/x509_five_user.der	 kernel_platform/common/security/samsung/five/x509_five_user.der
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_lv.c	 kernel_platform/common/security/samsung/five/five_lv.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_dsms.c	 kernel_platform/common/security/samsung/five/five_dsms.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_cache.h	 kernel_platform/common/security/samsung/five/five_cache.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/x509_five_eng.der	 kernel_platform/common/security/samsung/five/x509_five_eng.der
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_tee_interface.h	 kernel_platform/common/security/samsung/five/five_tee_interface.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_keyring.c	 kernel_platform/common/security/samsung/five/five_keyring.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/five/five_cert.h	 kernel_platform/common/security/samsung/five/five_cert.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm	 kernel_platform/common/security/samsung/defex_lsm
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/defex_packed_rules.inc	 kernel_platform/common/security/samsung/defex_lsm/defex_packed_rules.inc
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_immutable	 kernel_platform/common/security/samsung/defex_lsm/feature_immutable
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_immutable/defex_immutable.c	 kernel_platform/common/security/samsung/defex_lsm/feature_immutable/defex_immutable.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_immutable/kunit_test	 kernel_platform/common/security/samsung/defex_lsm/feature_immutable/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_immutable/kunit_test/defex_immutable_test.c 	 kernel_platform/common/security/samsung/defex_lsm/feature_immutable/kunit_test/defex_immutable_test.c 
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_immutable/kunit_test/Makefile	 kernel_platform/common/security/samsung/defex_lsm/feature_immutable/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/defex_packed_rules.bin	 kernel_platform/common/security/samsung/defex_lsm/defex_packed_rules.bin
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include	 kernel_platform/common/security/samsung/defex_lsm/include
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_config.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_config.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_tailer.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_tailer.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_caches.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_caches.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_test.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_test.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_internal.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_internal.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_rules.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_rules.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/ptree.h	 kernel_platform/common/security/samsung/defex_lsm/include/ptree.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_catch_list.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_catch_list.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_sign.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_sign.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/include/defex_debug.h	 kernel_platform/common/security/samsung/defex_lsm/include/defex_debug.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert	 kernel_platform/common/security/samsung/defex_lsm/cert
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert/defex_sign.c	 kernel_platform/common/security/samsung/defex_lsm/cert/defex_sign.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert/kunit_test	 kernel_platform/common/security/samsung/defex_lsm/cert/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert/kunit_test/defex_sign_test.c	 kernel_platform/common/security/samsung/defex_lsm/cert/kunit_test/defex_sign_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert/kunit_test/Makefile	 kernel_platform/common/security/samsung/defex_lsm/cert/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert/defex_cert.S	 kernel_platform/common/security/samsung/defex_lsm/cert/defex_cert.S
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert/x509_five_user.der	 kernel_platform/common/security/samsung/defex_lsm/cert/x509_five_user.der
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/cert/x509_five_eng.der	 kernel_platform/common/security/samsung/defex_lsm/cert/x509_five_eng.der
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm_utils.h	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm_utils.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm_log.h	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm_log.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm.h	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm_engine.h	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/include/dtm_engine.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/defex_trusted_map.c	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/defex_trusted_map.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_engine.c	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_engine.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm.c	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/kunit_test	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/kunit_test/Makefile	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/ptree.c	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/ptree.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_utils.c	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_utils.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_engine_defaultpolicy.h      	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_engine_defaultpolicy.h      
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_log.c	 kernel_platform/common/security/samsung/defex_lsm/feature_trusted_map/dtm_log.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/pack_rules	 kernel_platform/common/security/samsung/defex_lsm/pack_rules
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/defex_rules.c	 kernel_platform/common/security/samsung/defex_lsm/defex_rules.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_safeplace	 kernel_platform/common/security/samsung/defex_lsm/feature_safeplace
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/kunit_test	 kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/kunit_test/defex_safeplace_test.c 	 kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/kunit_test/defex_safeplace_test.c 
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/kunit_test/Makefile	 kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/defex_safeplace.c	 kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/defex_safeplace.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/defex_integrity.c	 kernel_platform/common/security/samsung/defex_lsm/feature_safeplace/defex_integrity.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/pack_rules.c	 kernel_platform/common/security/samsung/defex_lsm/pack_rules.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/Kconfig	 kernel_platform/common/security/samsung/defex_lsm/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine	 kernel_platform/common/security/samsung/defex_lsm/catch_engine
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_catch_list_test.c     	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_catch_list_test.c     
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_catch_list_compat_test.c 	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_catch_list_compat_test.c 
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_ht_test.c	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_ht_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_caches_test.c	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/defex_caches_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/Makefile	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_catch_list.c	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_catch_list.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_catch_list.inc	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_catch_list.inc
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_ht.c	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_ht.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_catch_list_compat.c	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_catch_list_compat.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_caches.c	 kernel_platform/common/security/samsung/defex_lsm/catch_engine/defex_caches.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection	 kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/defex_priv.c 	 kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/defex_priv.c 
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/kunit_test   	 kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/kunit_test   
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/kunit_test/Makefile 	 kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/kunit_test/Makefile 
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/kunit_test/defex_priv_test.c 	 kernel_platform/common/security/samsung/defex_lsm/feature_privilege_escalation_detection/kunit_test/defex_priv_test.c 
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/debug	 kernel_platform/common/security/samsung/defex_lsm/debug
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/debug/defex_debug.c	 kernel_platform/common/security/samsung/defex_lsm/debug/defex_debug.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/debug/kunit_test	 kernel_platform/common/security/samsung/defex_lsm/debug/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/debug/kunit_test/Makefile	 kernel_platform/common/security/samsung/defex_lsm/debug/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/debug/kunit_test/defex_debug_test.c	 kernel_platform/common/security/samsung/defex_lsm/debug/kunit_test/defex_debug_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core	 kernel_platform/common/security/samsung/defex_lsm/core
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/defex_get_mode.c	 kernel_platform/common/security/samsung/defex_lsm/core/defex_get_mode.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/defex_sysfs.c	 kernel_platform/common/security/samsung/defex_lsm/core/defex_sysfs.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/defex_rules_proc.c	 kernel_platform/common/security/samsung/defex_lsm/core/defex_rules_proc.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_rules_proc_test.c	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_rules_proc_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_common_test.c	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_common_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_lsm_test.c	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_lsm_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_sysfs_test.c	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_sysfs_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_get_mode_test.c	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_get_mode_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_main_test.c	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/defex_main_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/Makefile	 kernel_platform/common/security/samsung/defex_lsm/core/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/defex_tailer.c	 kernel_platform/common/security/samsung/defex_lsm/core/defex_tailer.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/defex_main.c	 kernel_platform/common/security/samsung/defex_lsm/core/defex_main.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/defex_common.c	 kernel_platform/common/security/samsung/defex_lsm/core/defex_common.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/core/defex_lsm.c	 kernel_platform/common/security/samsung/defex_lsm/core/defex_lsm.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/defex_lsm/Makefile	 kernel_platform/common/security/samsung/defex_lsm/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz	 kernel_platform/common/security/samsung/mz
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/include	 kernel_platform/common/security/samsung/mz/include
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/include/linux	 kernel_platform/common/security/samsung/mz/include/linux
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/include/linux/mz.h	 kernel_platform/common/security/samsung/mz/include/linux/mz.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_page.h	 kernel_platform/common/security/samsung/mz/mz_page.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_page.c	 kernel_platform/common/security/samsung/mz/mz_page.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_crypto.c	 kernel_platform/common/security/samsung/mz/mz_crypto.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz.c	 kernel_platform/common/security/samsung/mz/mz.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/Kconfig	 kernel_platform/common/security/samsung/mz/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_log.c	 kernel_platform/common/security/samsung/mz/mz_log.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_log.h	 kernel_platform/common/security/samsung/mz/mz_log.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz.h	 kernel_platform/common/security/samsung/mz/mz.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_mem.c	 kernel_platform/common/security/samsung/mz/mz_mem.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/test	 kernel_platform/common/security/samsung/mz/test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/test/security_mz_test.c	 kernel_platform/common/security/samsung/mz/test/security_mz_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/test/Makefile	 kernel_platform/common/security/samsung/mz/test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/Makefile	 kernel_platform/common/security/samsung/mz/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_internal.h	 kernel_platform/common/security/samsung/mz/mz_internal.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_page_v5_10.c	 kernel_platform/common/security/samsung/mz/mz_page_v5_10.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/mz/mz_ioctl.c	 kernel_platform/common/security/samsung/mz/mz_ioctl.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca	 kernel_platform/common/security/samsung/proca
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_certificate.asn1	 kernel_platform/common/security/samsung/proca/proca_certificate.asn1
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_table.c	 kernel_platform/common/security/samsung/proca/proca_table.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_config.c	 kernel_platform/common/security/samsung/proca/proca_config.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_task_descr.h	 kernel_platform/common/security/samsung/proca/proca_task_descr.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test	 kernel_platform/common/security/samsung/proca/kunit_test
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test/proca_identity_test.c	 kernel_platform/common/security/samsung/proca/kunit_test/proca_identity_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test/five	 kernel_platform/common/security/samsung/proca/kunit_test/five
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test/five/Makefile	 kernel_platform/common/security/samsung/proca/kunit_test/five/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test/proca_test_certificate.h	 kernel_platform/common/security/samsung/proca/kunit_test/proca_test_certificate.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test/proca_table_test.c	 kernel_platform/common/security/samsung/proca/kunit_test/proca_table_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test/proca_certificate_test.c	 kernel_platform/common/security/samsung/proca/kunit_test/proca_certificate_test.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/kunit_test/Makefile	 kernel_platform/common/security/samsung/proca/kunit_test/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/security_proca.py	 kernel_platform/common/security/samsung/proca/security_proca.py
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/Kconfig	 kernel_platform/common/security/samsung/proca/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf	 kernel_platform/common/security/samsung/proca/gaf
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf/gaf_v3.c	 kernel_platform/common/security/samsung/proca/gaf/gaf_v3.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf/gaf_v4.c	 kernel_platform/common/security/samsung/proca/gaf/gaf_v4.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf/gaf_v5.c	 kernel_platform/common/security/samsung/proca/gaf/gaf_v5.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf/gaf_v6.c	 kernel_platform/common/security/samsung/proca/gaf/gaf_v6.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf/Kconfig	 kernel_platform/common/security/samsung/proca/gaf/Kconfig
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf/proca_gaf.h	 kernel_platform/common/security/samsung/proca/gaf/proca_gaf.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/gaf/Makefile	 kernel_platform/common/security/samsung/proca/gaf/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_certificate.c	 kernel_platform/common/security/samsung/proca/proca_certificate.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_porting.h	 kernel_platform/common/security/samsung/proca/proca_porting.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_lsm.c	 kernel_platform/common/security/samsung/proca/proca_lsm.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_task_descr.c	 kernel_platform/common/security/samsung/proca/proca_task_descr.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_identity.c	 kernel_platform/common/security/samsung/proca/proca_identity.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_table.h	 kernel_platform/common/security/samsung/proca/proca_table.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_fcntl.c	 kernel_platform/common/security/samsung/proca/proca_fcntl.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/Makefile	 kernel_platform/common/security/samsung/proca/Makefile
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/s_os	 kernel_platform/common/security/samsung/proca/s_os
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/s_os/proca_lsm.c	 kernel_platform/common/security/samsung/proca/s_os/proca_lsm.c
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_certificate.h	 kernel_platform/common/security/samsung/proca/proca_certificate.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_config.h	 kernel_platform/common/security/samsung/proca/proca_config.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_identity.h	 kernel_platform/common/security/samsung/proca/proca_identity.h
cp -r  	/home/user/UltraS23/kernel_platform/common/security/samsung/proca/proca_log.h	 kernel_platform/common/security/samsung/proca/proca_log.h
cp -r  	/home/user/UltraS23/kernel_platform/common/init/Kconfig.gki-debug	 kernel_platform/common/init/Kconfig.gki-debug
cp -r  	/home/user/UltraS23/kernel_platform/common/kernel/trace/trace_tracing_mark_write.c	 kernel_platform/common/kernel/trace/trace_tracing_mark_write.c

