cp /home/user/UltraS23/kernel_platform/common/arch/arm64/configs/gki_defconfig kernel_platform/common/arch/arm64/configs/gki_defconfig
cp /home/user/UltraS23/kernel_platform/common/Makefile  kernel_platform/common/Makefile 
cp /home/user/UltraS23/kernel_platform/common/arch/Kconfig  kernel_platform/common/arch/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/Kconfig  kernel_platform/common/arch/arm64/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/configs/defconfig  kernel_platform/common/arch/arm64/configs/defconfig 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/configs/gki_defconfig  kernel_platform/common/arch/arm64/configs/gki_defconfig 
cp /home/user/UltraS23/kernel_platform/common/arch/arm64/kernel/Makefile  kernel_platform/common/arch/arm64/kernel/Makefile 
cp /home/user/UltraS23/kernel_platform/common/arch/um/Kconfig  kernel_platform/common/arch/um/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/arch/um/kernel/Makefile  kernel_platform/common/arch/um/kernel/Makefile 
cp /home/user/UltraS23/kernel_platform/common/arch/x86/configs/gki_defconfig  kernel_platform/common/arch/x86/configs/gki_defconfig 
cp /home/user/UltraS23/kernel_platform/common/block/Kconfig  kernel_platform/common/block/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/build.config.common  kernel_platform/common/build.config.common 
cp /home/user/UltraS23/kernel_platform/common/build.config.gki.aarch64  kernel_platform/common/build.config.gki.aarch64 
cp /home/user/UltraS23/kernel_platform/common/crypto/Kconfig  kernel_platform/common/crypto/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/crypto/Makefile  kernel_platform/common/crypto/Makefile 
cp /home/user/UltraS23/kernel_platform/common/drivers/Makefile  kernel_platform/common/drivers/Makefile 
cp /home/user/UltraS23/kernel_platform/common/drivers/base/Kconfig  kernel_platform/common/drivers/base/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/drivers/base/Makefile  kernel_platform/common/drivers/base/Makefile 
cp /home/user/UltraS23/kernel_platform/common/drivers/block/zram/Kconfig  kernel_platform/common/drivers/block/zram/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/drivers/connector/Kconfig  kernel_platform/common/drivers/connector/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/drivers/dma-buf/Makefile  kernel_platform/common/drivers/dma-buf/Makefile 
cp /home/user/UltraS23/kernel_platform/common/drivers/dma-buf/heaps/Kconfig  kernel_platform/common/drivers/dma-buf/heaps/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/drivers/md/Makefile  kernel_platform/common/drivers/md/Makefile 
cp /home/user/UltraS23/kernel_platform/common/drivers/staging/android/Kconfig  kernel_platform/common/drivers/staging/android/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/drivers/staging/android/Makefile  kernel_platform/common/drivers/staging/android/Makefile 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/Kconfig  kernel_platform/common/drivers/usb/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/core/Kconfig  kernel_platform/common/drivers/usb/core/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/drivers/usb/core/Makefile  kernel_platform/common/drivers/usb/core/Makefile 
cp /home/user/UltraS23/kernel_platform/common/fs/Kconfig  kernel_platform/common/fs/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/fs/Makefile  kernel_platform/common/fs/Makefile 
cp /home/user/UltraS23/kernel_platform/common/fs/crypto/Makefile  kernel_platform/common/fs/crypto/Makefile 
cp /home/user/UltraS23/kernel_platform/common/fs/f2fs/Kconfig  kernel_platform/common/fs/f2fs/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/fs/fat/Kconfig  kernel_platform/common/fs/fat/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/fs/fuse/Kconfig  kernel_platform/common/fs/fuse/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/fs/proc/Kconfig  kernel_platform/common/fs/proc/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/fs/proc/Makefile  kernel_platform/common/fs/proc/Makefile 
cp /home/user/UltraS23/kernel_platform/common/init/Kconfig  kernel_platform/common/init/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/kernel/power/Kconfig  kernel_platform/common/kernel/power/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/kernel/trace/Makefile  kernel_platform/common/kernel/trace/Makefile 
cp /home/user/UltraS23/kernel_platform/common/lib/Kconfig.debug  kernel_platform/common/lib/Kconfig.debug 
cp /home/user/UltraS23/kernel_platform/common/lib/kunit/Kconfig  kernel_platform/common/lib/kunit/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/lib/kunit/Makefile  kernel_platform/common/lib/kunit/Makefile 
cp /home/user/UltraS23/kernel_platform/common/mm/Kconfig  kernel_platform/common/mm/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/mm/Makefile  kernel_platform/common/mm/Makefile 
cp /home/user/UltraS23/kernel_platform/common/net/Kconfig  kernel_platform/common/net/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/net/Makefile  kernel_platform/common/net/Makefile 
cp /home/user/UltraS23/kernel_platform/common/net/netfilter/Makefile  kernel_platform/common/net/netfilter/Makefile 
cp /home/user/UltraS23/kernel_platform/common/scripts/setlocalversion  kernel_platform/common/scripts/setlocalversion 
cp /home/user/UltraS23/kernel_platform/common/security/Kconfig  kernel_platform/common/security/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/security/Makefile  kernel_platform/common/security/Makefile 
cp /home/user/UltraS23/kernel_platform/common/sound/soc/samsung/Kconfig  kernel_platform/common/sound/soc/samsung/Kconfig 
cp /home/user/UltraS23/kernel_platform/common/tools/testing/kunit/configs/default.config  kernel_platform/common/tools/testing/kunit/configs/default.config 

